# Generated by Django 2.1.4 on 2019-01-10 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='user_profile_pic',
            field=models.ImageField(blank=True, upload_to='user_profile_pic'),
        ),
    ]
