# Generated by Django 2.1.4 on 2019-01-10 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0002_auto_20190110_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='user_profile_pic',
            field=models.ImageField(blank=True, upload_to='profile_pics'),
        ),
    ]
